### ISSUE TITLE
Error running calculate-tin.py

### ISSUE THREAD

**Issue by rpauly** [zavolanlab/tin-score-calculation#31]
Hi!
I was trying to run:
calculate-tin.py -i Sample_A.bam -r hg19_Ensembl_gene.bed
But I get an error:
```
@ 2024-03-15 16:00:51: Get BAM file(s) ...
Total 1 BAM file(s):
	  Sample_A.bam
Traceback (most recent call last):
  File "/home/paulyr2/.local/bin/calculate-tin.py", line 4, in <module>
    __import__('pkg_resources').run_script('tin-score-calculation==0.6.3', 'calculate-tin.py')
  File "/mnt/nasapps/production/miniconda/23.1.0/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/nasapps/production/miniconda/23.1.0/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/home/paulyr2/.local/lib/python3.10/site-packages/tin_score_calculation-0.6.3-py3.10.egg/EGG-INFO/scripts/calculate-tin.py", line 554, in <module>
  File "/home/paulyr2/.local/lib/python3.10/site-packages/tin_score_calculation-0.6.3-py3.10.egg/EGG-INFO/scripts/calculate-tin.py", line 490, in main
AttributeError: 'NoneType' object has no attribute 'split'
```
**head hg19_Ensembl_gene.bed**
`chr1	66999065	67210057	ENST00000237247	0	+	67000041	67208778	0	27	25,123,64,25,84,57,55,176,12,12,25,52,86,93,75,501,81,128,127,60,112,156,133,203,65,165,1302,	0,863,92464,99687,100697,106394,109427,110161,127130,134147,137612,138561,139898,143621,146295,148486,150724,155765,156807,162051,185911,195881,200365,205952,207275,207889,209690,`

**Comment by uniqueg** [comment]
Thanks for reporting @rpauly!

At a quick glance, it seems that the way the code is written, indicating names for each sample with the `--names` option is required - even though it shouldn't be (and the docs don't say so).

Can you try if it works if you add something like `--names Sample_A` to your call?

```sh
calculate-tin.py -i Sample_A.bam --names Sample_A -r hg19_Ensembl_gene.bed
```

We successfully use the script in a Snakemake workflow where it is called [like this](https://github.com/zavolanlab/zarp/blob/ac953471b475b9f1b81ac08679d01fc4c2f98d9d/workflow/Snakefile#L937C1-L943C48) (simplified):

```sh
calculate-tin.py \
  -i BAM_FILE \
  -r BED12_FILE \
  --names SAMPLE_NAMES \
  -p THREADS \
  > OUT.STDOUT 2> OUT.STDERR
```

So, presumably adding `--names` should fix your problem. But please tell us if not :pray: 

We will also update either the code (probably) or the docs in a future release (but that might take some time).

---

Notes to our group to debug this later (@AngryMaciek @mzavolan):

The offending line is [this one](https://github.com/zavolanlab/tin-score-calculation/blame/527ee69f0bfe105d1fe0db92e9dd91b3ec5bbdd3/scripts/calculate-tin.py#L490):

```py
    names = options.sample_names.split(",")
```

with `options.sample_names` coming from `--names`, as defined [here](https://github.com/zavolanlab/tin-score-calculation/blame/527ee69f0bfe105d1fe0db92e9dd91b3ec5bbdd3/scripts/calculate-tin.py#L416-L425C6) (without any further modifications):

```py
    parser.add_option(
        "--names",
        dest="sample_names",
        action="store",
        type="string",
        help=(
            "sample names, comma separated (no spaces allowed); number must "
            "match the number of provided bam_files"
        ),
    )
```

There is no explicit default provided for `sample_names` and so it is assigned `None` when the user does not provide `--names`. And that will of course break when the script attempts to `.split()` it.
